### ISSUE TITLE
Wrong Output Q5-Assignment 2

### ISSUE THREAD

**Issue by theydvgaurav** [saksham0302/siemens_assignments#2]
Code breaks when the user enters the name. Attaching the screenshot for reference.
![Screenshot from 2022-06-18 19-21-19](https://user-images.githubusercontent.com/54793655/174441594-cb4a7299-2567-4376-9ac4-132b7c260932.png)

**Comment by saksham0302** [comment]
Thank you for reviewing the code. The issue has been resolved, please find the attachment below for a sample output.

![Screenshot 2022-06-19 142601](https://user-images.githubusercontent.com/106727109/174473395-7cbda9d2-c056-4cf9-a351-6234de1da836.png)
