### ISSUE TITLE
Incorrect Input Handling - Q5A2

### ISSUE THREAD

**Issue by theydvgaurav** [saksham0302/siemens_assignments#3]
The user is allowed to enter any value, with no check being implemented for incorrect input.
![Screenshot from 2022-06-19 18-22-40](https://user-images.githubusercontent.com/54793655/174481929-720ccd38-481b-4cf3-942f-f5da0511d6a6.png)

**Comment by saksham0302** [comment]
Thank you for reviewing the code. Please find the attachment below for a sample output

![Screenshot 2022-06-19 193154](https://user-images.githubusercontent.com/106727109/174485054-07b4b8a7-8288-44e2-bfb5-cd5e3a38e56c.png)
